# -*- coding: utf-8 -*-
"""CS01-17.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11CsMUfEFQfhIWvGHIB03GiHiFCZFJrBP
"""

import numpy as np
from numpy import random
x = random.randint(100,size=(5,10))
print(np.sort(x))